### ISSUE TITLE
osc-covert on Ice Lake

### ISSUE THREAD

**Issue by jamchamb** [zzrcxb/LLCFeasible#6] opened 2024-10-07 16:55 UTC
Running `osc-covert` on Ice Lake always failed at building the main SF eviction set due to the `evset->size < SF_ASSOC + extra_sf_cong` check in `check_and_set_sf_evset`. I think it was due to `SF_ASSOC` begin defined as 16 for Ice Lake, and `extra_sf_cong` never being set or used earlier in `osc-covert`.

I followed what the other programs do to set it and change the SF config, does this seem correct?

```diff
diff --git a/src/osc-covert.c b/src/osc-covert.c
index b9e8f11..2bd01af 100644
--- a/src/osc-covert.c
+++ b/src/osc-covert.c
@@ -18,11 +18,17 @@ static evchain *sf_chain1 = NULL, *sf_chain2 = NULL;
 static u32 extra_sf_cong = 0; // extra_cong wrt. SF!

 static bool check_and_set_sf_evset(EVSet *evset) {
-    if (!evset || evset->size < SF_ASSOC + extra_sf_cong) {
+    if (!evset || evset->size < SF_ASSOC) {
         _error("Failed to build sf evset\n");
+        if (!evset) {
+            _error("evset is NULL\n");
+        } else {
+            _error("evset->size = %u, less than %u\n",
+                evset->size, SF_ASSOC);
+        }
         return false;
     }
-    evset->size = SF_ASSOC + extra_sf_cong;
+    evset->size = SF_ASSOC;

     EVTestRes tres = precise_evset_test_alt(target, evset);
     if (tres != EV_POS) {
@@ -92,6 +98,8 @@ EVSet *prepare_evsets() {
     EVBuildConfig sf_config;
     default_skx_sf_evset_build_config(&sf_config, NULL, l2_evset, &hctrl);

+    sf_config.algo_config.extra_cong = extra_sf_cong;
+
     EVSet *sf_evset = build_skx_sf_EVSet(target, &sf_config, NULL);
     helper_sf_evset = build_skx_sf_EVSet(target, &sf_config, NULL);

@@ -484,5 +492,10 @@ int main(int argc, char **argv) {
         _error("Failed to initialize cache env!\n");
         return EXIT_FAILURE;
     }
+
+    extra_sf_cong = SF_ASSOC - detected_l3->n_ways;
+    _info("SF_ASSOC: %u, l3 n_ways: %u, extra_sf_cong: %u\n",
+        SF_ASSOC, detected_l3->n_ways, extra_sf_cong);
+
     return covert_recv();
 }
 ```

This will run for me, though with the default options the number of sender evicts and detects is very low (usually 0 to 5, sometimes up to 10 or 20 out of 100 emits). I also get this error often:

```
WARN: Bad threshold!
ERROR: Failed to calibrate grp access lat!
ERROR: Failed to prepare evset
```

The CPU is a Xeon Platinum 8375C:

```
---------------------------------------------------------                                                                                                                                                                                     
Level 1 cache; Type: Data cache; Size: 48kB                                                                                                                                                                                                   
Self init: 1; Fully Assoc.: 0; Inclu.: 0; Complex Idx: 0                                                                                                                                                                                      
Line size: 64B; #Sets: 64; #Ways: 12; #Slices: 1                                                                                                                                                                                              
---------------------------------------------------------                                                                                                                                                                                     
---------------------------------------------------------                                                                                                                                                                                     
Level 1 cache; Type: Inst. cache; Size: 32kB                                                                                                                                                                                                  
Self init: 1; Fully Assoc.: 0; Inclu.: 0; Complex Idx: 0                                                                                                                                                                                      
Line size: 64B; #Sets: 64; #Ways: 8; #Slices: 1                                                                                                                                                                                               
---------------------------------------------------------                                                                                                                                                                                     
---------------------------------------------------------                                                                                                                                                                                     
Level 2 cache; Type: Unified cache; Size: 1280kB                                                                                                                                                                                              
Self init: 1; Fully Assoc.: 0; Inclu.: 0; Complex Idx: 0                                                                                                                                                                                      
Line size: 64B; #Sets: 1024; #Ways: 20; #Slices: 1                                                                                                                                                                                            
---------------------------------------------------------                                                                                                                                                                                     
---------------------------------------------------------                                                                                                                                                                                     
Level 3 cache; Type: Unified cache; Size: 54MB                                                                                                                                                                                                
Self init: 1; Fully Assoc.: 0; Inclu.: 0; Complex Idx: 1                                                                                                                                                                                      
Line size: 64B; #Sets: 2048; #Ways: 12; #Slices: 36                                                                                                                                                                                           
---------------------------------------------------------    
```

**Comment by zzrcxb** [comment] 2024-10-07 20:35
Hi! Thank you for reporting this issue. Indeed, the code in this repo is mostly tested on Skylake (SKX) and some of them are specialized to SKX (e.g., osc-covert.c).

The `extra_sf_cong` is not the issue as it is set to `0`. The variable was defined for some other purposes but I forgot to remove it in the release. Sorry about the confusion.

The reason why SF eviction set construction failed is because I did not set the `extra_cong` in the algorithm configuration based on the uarch, as my implementation assumed SKX. Because IceLake (ICX) has more SF ways than SKX, the default value `extra_cong=1` for SKX doesn't work for ICX. It's now fixed.

The error of `WARN: Bad threshold!` is an indication that the probe cannot reliably distinguish whether an SF set is accessed or not. The root cause of this issue is that the asm-based parallel probe assumes the SF's associativity is 12 while it should be 16 for ICX. I've fixed it by adding an asm version for ICX and falling back to the noasm version if the uarch is not Skylake, Cascade Lake, or IceLake. The current version should work on ICX now.

**Comment by zzrcxb** [comment] 2024-10-07 22:43
Updated the previous comment. Please let me know if it works on your end now. Thank you!

**Comment by jamchamb** [comment] 2024-10-08 15:07
Thanks, it's working much more reliably now.

**Comment by zzrcxb** [comment] 2024-10-08 15:10
Glad to hear that. If there's no other issues, do you mind if I close this issue?

**Closed as completed** 2024-10-08 15:29 UTC
Labels: IceLake, compatibility
